# Generated by Django 5.1.1 on 2024-10-10 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Last Name')),
                ('contact_number', models.BigIntegerField(blank=True, null=True, verbose_name='Contact Number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time of Commute')),
                ('start_latitude', models.FloatField(blank=True, verbose_name='Starting Place Latitude')),
                ('start_longitude', models.FloatField(blank=True, verbose_name='Starting Place Longitude')),
                ('start_name', models.TextField(blank=True, verbose_name='Starting Place')),
                ('end_latitude', models.FloatField(blank=True, verbose_name='Ending Place Latitude')),
                ('end_longitude', models.FloatField(blank=True, verbose_name='Ending Place Longitude')),
                ('end_name', models.TextField(blank=True, verbose_name='Ending Place Name')),
                ('seats', models.IntegerField()),
                ('participants', models.ManyToManyField(blank=True, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts_trip', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
